### ISSUE TITLE
Including `jq` as a default systemPackages

### ISSUE THREAD

**Issue by PierreR** [zimbatm/nixbox#16]
I am not sure it is a good idea as it might increase the size of the box.

Anyhow while working on distributing a `devbox`, I have had to fight with regex quite a bit to achieve what I wanted without `jq`:

https://github.com/CIRB/devbox/commit/82f851e37a25832b5176bf0f1befbc2e80fed27c

What do you think ?

Of course I can always build a custom box with packer ( I have been trying to avoid that until now). So really not a big deal either way.

**Comment by zimbatm** [comment]
Sure I don't mind adding it. One issue that you might encounter would be that because the installation replaces the current system, the new configuration.nix must make sure to also include `jq`. Alternatively you could fetch and parse the version using ruby and inject that somehow into the install script.

**Comment by PierreR** [comment]
I am OK with that. I will PR the change.

What I do in my shell package provisioner (`vagrantFile`) is to replace `configuration.nix` so it is clear that the old one has no impact after the 'bootstrap phase'.

It looks cleaner to me : I have one configuration.nix that represent the state of the devbox I want. The only file that is not replaced is `hardware-configuration.nix`

**Comment by zimbatm** [comment]
Thanks!
